POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password",
  "role": "USER",
  "firstName": "John",
  "lastName": "Doe",
  "profileImageUrl": "https://cdn-icons-png.flaticon.com/512/3135/3135715.png"
}

###

POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "seller1@example.com",
  "password": "password",
  "firstName": "Mircle",
  "lastName": "Jackson",
  "profileImageUrl": "https://cdn-icons-png.flaticon.com/512/3135/3135715.png"
  "role": "SELLER"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "seller1@example.com",
  "password": "password"
}
