### get all auctioning products
GET http://localhost:8080/api/v1/products
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMUBleGFtcGxlLmNvbSIsImlzcyI6Ik1JVSIsImlhdCI6MTY5ODE5ODI2OCwiZXhwIjoxNjk4NTU4MjY4LCJyb2xlIjoiVVNFUiJ9.ML2poFVG7aTmluvcLXm_ss3xO4za7cT942WYuRMjoJFiMLu3XZHizWfYqInuNUXC31LKGDuTpdb7rhe2q9DXGg


### get all auctioning products search by name
GET http://localhost:8080/api/v1/products?name=iPhone


### get product by id
GET http://localhost:8080/api/v1/products/1
