### add new product
POST http://localhost:8080/api/seller/v1/products
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTA3ODI1LCJleHAiOjE2OTg0Njc4MjUsInJvbGUiOiJTRUxMRVIifQ.rzD5au3NR4fkzHt9zlV1IM9SFOY961la2tpOq85mJuZbGQbWCfpjOyJnpTNVjhfWX16mwxfWQxWl-MCAWutJiA
Content-Type: application/json

{
  "title": "iPhone 14 pro max",
  "description": "good condition",
  "imageUrl": "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
  "categories": [
    {"name": "phone"},
    {"name":  "iphone"}
  ],
  "released": true,
  "startPrice": 599,
  "depositAmount": 59.9,
  "bidDueDateTime": "2023-10-22T13:56:39.492",
  "payDate": "2023-10-23"
}


### get all products by seller
GET http://localhost:8080/api/seller/v1/products
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTA3ODI1LCJleHAiOjE2OTg0Njc4MjUsInJvbGUiOiJTRUxMRVIifQ.rzD5au3NR4fkzHt9zlV1IM9SFOY961la2tpOq85mJuZbGQbWCfpjOyJnpTNVjhfWX16mwxfWQxWl-MCAWutJiA

### get all released products by seller id
GET http://localhost:8080/api/seller/v1/products?released=true
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTA3ODI1LCJleHAiOjE2OTg0Njc4MjUsInJvbGUiOiJTRUxMRVIifQ.rzD5au3NR4fkzHt9zlV1IM9SFOY961la2tpOq85mJuZbGQbWCfpjOyJnpTNVjhfWX16mwxfWQxWl-MCAWutJiA

### get product by id
GET http://localhost:8080/api/seller/v1/products/1
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTA3ODI1LCJleHAiOjE2OTg0Njc4MjUsInJvbGUiOiJTRUxMRVIifQ.rzD5au3NR4fkzHt9zlV1IM9SFOY961la2tpOq85mJuZbGQbWCfpjOyJnpTNVjhfWX16mwxfWQxWl-MCAWutJiA

### get all unreleased products by seller id
GET http://localhost:8080/api/seller/v1/products?released=false
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTA3ODI1LCJleHAiOjE2OTg0Njc4MjUsInJvbGUiOiJTRUxMRVIifQ.rzD5au3NR4fkzHt9zlV1IM9SFOY961la2tpOq85mJuZbGQbWCfpjOyJnpTNVjhfWX16mwxfWQxWl-MCAWutJiA


### update an unreleased product
PUT http://localhost:8080/api/seller/v1/products/1
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTA3ODI1LCJleHAiOjE2OTg0Njc4MjUsInJvbGUiOiJTRUxMRVIifQ.rzD5au3NR4fkzHt9zlV1IM9SFOY961la2tpOq85mJuZbGQbWCfpjOyJnpTNVjhfWX16mwxfWQxWl-MCAWutJiA
Content-Type: application/json

{
  "title": "iPhone 14 pro max",
  "description": "good condition",
  "categories": [
    {"name":  "iphone"}
  ],
  "released": false,
  "startPrice": 499,
  "depositAmount": 50,
  "bidDueDateTime": "2023-10-22T13:56:39.492",
  "payDate": "2023-10-25"
}


### delete an unreleased product
DELETE http://localhost:8080/api/seller/v1/products/1
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MDAxNjMyLCJleHAiOjE2OTgwMDUyMzIsInJvbGUiOiJTRUxMRVIifQ.vg2qfyhgYuStBjK0n2uRI5s9bwyuI5ylR6pTOncDeDBY4GFaHxp8SlAq6UrSsuR8OuoF45XV8bSgshxKbvPgVg

### Get all Categories
GET http://localhost:8080/api/seller/v1/categories
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXIxQGV4YW1wbGUuY29tIiwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTkwOTIzLCJleHAiOjE2OTg1NTA5MjMsInJvbGUiOiJTRUxMRVIifQ.QhYP3BV6yhPH7wMUD3C0fbZ0nxkUrMOdetxVHsRlhorp9X5Bc4vt29Z06tqVFpN85oXUPIym_y8nrluyNWrvPw
